name: CI-github-pr-workitem-validator
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Get PR context
      id: pr-context
      run: |
        Write-Host "PR# ${{ github.event.pull_request.number }}"

        $getPullRequestUri = "https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}"

        Write-Host $getPullRequestUri

        $pullRequestData = Invoke-WebRequest -Uri $getPullRequestUri -Headers @{'Accept' = 'application/json'; 'Authorization' = 'token ${{github.token}}'}

        Write-Host $pullRequestData
      shell: pwsh
